#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

sh -n "$ROOT/companion/embedded/watchdog.sh"
bash -n "$ROOT/scripts/install.sh"
bash -n "$ROOT/scripts/harden.sh"
bash -n "$ROOT/scripts/status.sh"
bash -n "$ROOT/scripts/sync-ui.sh"
node --check "$ROOT/companion/reference-node/public/app.js"
node --check "$ROOT/companion/reference-node/public/studio.js"
node --check "$ROOT/companion/reference-node/public/studio-i18n.js"
node --check "$ROOT/companion/reference-node/public/i18n.js"
node --check "$ROOT/companion/reference-node/public/native-pages.js"
bash "$ROOT/test/install-script.test.sh"
bash "$ROOT/test/harden-script.test.sh"

diff -q "$ROOT/companion/reference-node/public/index.html" "$ROOT/companion/embedded/public/index.html"
diff -q "$ROOT/companion/reference-node/public/app.js" "$ROOT/companion/embedded/public/app.js"
diff -q "$ROOT/companion/reference-node/public/studio.js" "$ROOT/companion/embedded/public/studio.js"
diff -q "$ROOT/companion/reference-node/public/studio-i18n.js" "$ROOT/companion/embedded/public/studio-i18n.js"
diff -q "$ROOT/companion/reference-node/public/stream-builders.js" "$ROOT/companion/embedded/public/stream-builders.js"
diff -q "$ROOT/companion/reference-node/public/i18n.js" "$ROOT/companion/embedded/public/i18n.js"
diff -q "$ROOT/companion/reference-node/public/native-pages.js" "$ROOT/companion/embedded/public/native-pages.js"
diff -q "$ROOT/companion/reference-node/public/logo.svg" "$ROOT/companion/embedded/public/logo.svg"
diff -q "$ROOT/companion/reference-node/public/styles.css" "$ROOT/companion/embedded/public/styles.css"

test -s "$ROOT/README.md"
test -s "$ROOT/README.fr.md"
test -s "$ROOT/README.zh-CN.md"
test -s "$ROOT/LICENSE"
test -s "$ROOT/SECURITY.md"
test -s "$ROOT/CONTRIBUTING.md"
test -s "$ROOT/docs/assets/logo.svg"
test -s "$ROOT/docs/assets/screenshot-guide.png"
test -s "$ROOT/docs/assets/screenshot-studio.png"
test -s "$ROOT/docs/assets/screenshot-streaming.png"
test -s "$ROOT/docs/assets/screenshot-autodirector.png"
test -s "$ROOT/docs/assets/social-preview.png"
grep -Fq 'README.fr.md' "$ROOT/README.md"
grep -Fq 'README.md' "$ROOT/README.fr.md"
grep -Fq 'README.zh-CN.md' "$ROOT/README.md"
grep -Fq 'README.zh-CN.md' "$ROOT/README.fr.md"
grep -Fq 'README.md' "$ROOT/README.zh-CN.md"
grep -Fq 'README.fr.md' "$ROOT/README.zh-CN.md"
grep -Fq './scripts/install.sh <LINKPI_IP>' "$ROOT/README.md"
grep -Fq './scripts/install.sh <IP_LINKPI>' "$ROOT/README.fr.md"
grep -Fq './scripts/install.sh <LINKPI_IP>' "$ROOT/README.zh-CN.md"
grep -Fq 'LinkPi Companion' "$ROOT/README.md"
grep -Fq 'LinkPi Companion' "$ROOT/README.fr.md"
grep -Fq 'docs/assets/screenshot-guide.png' "$ROOT/README.md"
grep -Fq 'docs/assets/screenshot-guide.png' "$ROOT/README.fr.md"
grep -Fq 'docs/assets/screenshot-guide.png' "$ROOT/README.zh-CN.md"
grep -Fq 'Guide' "$ROOT/README.fr.md"

(
  cd "$ROOT/companion/reference-node"
  npm test
)

echo "Local validation passed."
